# -----------  Agents  -----------
[[agents]]
id = "test_agent3"
name = "Agent 3"
public_address = "HcSCIREnuI7mbpvmdi6Hd9hzJnPB39x7rb7B9rKQNc3q33n3D98IJciPiMj8jqr"
keystore_file = "conductor/agent3.keystore"

# -----------  DNA  -----------
[[dnas]]
id = "coolcats_dna"
file = "dna-src/dist/coolcats.dna.json"
hash = "QmVAUrCBVBsdigWH5pvk3t4cd7Khnrz9uxfHNgK1AyBZbu"

[[instances]]
id = "coolcats_instance3"
agent = "test_agent3"
dna = "coolcats_dna"
[instances.storage]
type = "memory"

[[interfaces]]
id = "websocket_interface3"
[interfaces.driver]
type = "websocket"
port = 8890
[[interfaces.instances]]
id = "coolcats_instance3"

# -----------  UI  -----------
[[ui_bundles]]
id = "coolcats3_ui"
root_dir = "ui-src/target/deploy"

[[ui_interfaces]]
id = "ui-interface3"
bundle = "coolcats3_ui"
port = 8002
dna_interface = "websocket_interface3"

[network]
type="n3h"
n3h_persistence_path = "/tmp/n3h/3"
bootstrap_nodes = []

[logger]
type = "simple"
