# -----------  Agents  -----------
[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcSCICF4Hgx3K9frixvZexQde9Igv5uz83e5i9oQcYnRv8i8bPUQY4buSpndeka"
keystore_file = "conductor/agent2.keystore"

# -----------  DNA  -----------
[[dnas]]
id = "coolcats_dna"
file = "dist/coolcats.dna.json"
hash = "QmSWPkxapsvSJKZMtagXdxBsPEi7Lb48PwA9Aya5E7DLh8"

[[instances]]
id = "coolcats_instance2"
agent = "test_agent2"
dna = "coolcats_dna"
[instances.storage]
type = "memory"

[[interfaces]]
id = "websocket_interface2"
[interfaces.driver]
type = "websocket"
port = 8889
[[interfaces.instances]]
id = "coolcats_instance2"

# -----------  UI  -----------
[[ui_bundles]]
id = "coolcats_ui2"
root_dir = "ui/target/deploy"

[[ui_interfaces]]
id = "ui-interface2"
bundle = "coolcats_ui2"
port = 8001
dna_interface = "websocket_interface2"

[network]
type="n3h"
n3h_persistence_path = "/tmp/n3h/2"
bootstrap_nodes = []

[logger]
type = "simple"
