[package]
name = "wildcat-proc-macros"
version = "0.1.0"
authors = ["Michael Goldman <mike.goldman@allstreets.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-quote = "0.3.0"
syn = "1.0.5"
