[package]
name = "coolcats-holoclient"
version = "0.2.0"
authors = ["Michael Goldman <mike.goldman@allstreets.org>"]
edition = "2018"

[dependencies]
coolcats-utils = { path = "../utils" }
json = "0.11.15"
serde = { version = "1.0.101", features = ["derive"] }
stdweb = "0.4.18"
yew = "0.8.0"
